name: avatar_hover
description: Library to create on hover menu, and avatar containers with complete customization and more to come
version: 1.0.2
homepage: https://github.com/WaterBlueNewWorld/avatar_hover

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  morphable_shape: ^1.5.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
